import { twMerge } from 'tailwind-merge'
import { Inter, Noto_Sans_KR } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const notoSansKR = Noto_Sans_KR({ weight: ['400', '500'], preload: false })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          notoSansKR.className,
          'bg-blue-50',
          'text-blue-900',
          'antialiased'
        )}
      >
        {children}
      </body>
    </html>
  )
}
